### PR TITLE
Add Inferno colormap

### PR DESCRIPTION
**Pull request by BatchDrake**
This PR provides support for the Inferno colormap. It was implemented by comparative method with respect to existing colormaps  and from the existing Matplotlib's LUT (https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/_cm_listed.py).

**Please note:** the code builds but I didn't have any PlutoSDR at hand now to test it. While the code is fairly simple and adds no new logic to the software, I still miss some testing on it. Feel free to take this PR as a WIP if the colormap does not look right.

### CODE REVIEW

**Comment by daniestevez** [comment]
Thanks! Looks good to me. I tested the firmware image from one of the earlier CI runs. Can you squash the commits before I merge this?

**Comment by BatchDrake** [comment]
On it

**Comment by BatchDrake** [comment]
Done!

**Comment by daniestevez** [comment]
Looks good. To be merged once the CI finishes.

**Pull request merged**
